### ISSUE TITLE
SignReferences.txt - fallback in folder hierarchy

### ISSUE THREAD

**Issue by vatirim** [picrap/SignReferences#2]
Hi,
congrats on your helpful package, I was just about to hack sth on my own before finding your package.

My _use case_: several of my projects include the same unsigned nuget package and I don't want to create multiple SignReferences.txt files.

_Idea/Feature request_:
Why not do it like nuget with the nuget.config file or git with .gitignore: Search for the file on all parent folders and merge the result? Packages used multiple times could be on a top level and specific packages on the project level.

Greetings from Haute-Savoie !

**Comment by picrap** [comment]
Good idea, it could also look for the file in the solution folder.

**Comment by picrap** [comment]
I just did a blind fix (no time for more tonight) in version 1.1. Let me know if it works. If not, I'll test it :wink: 
Et puis bon, c'est comme ça et puis c'est tout :fr:

**Comment by vatirim** [comment]
It works, thanks. The solution directory as a fallback is ok for my current use case. But I have worked on repositories with multiple solutions that are not in the same folder, so the parent folder fallback may still be nice to have.
Merci bcp, aussi pour la solution rapide !

**Comment by picrap** [comment]
It's not that I enjoy saying "no", but the project directory may not be a child of the solution directory, so "climbing up" the project directories is problematic since the application may not know where to stop.
If you have a suggestion, great, otherwise, I'll close the issue.

**Comment by vatirim** [comment]
Nuget seems to walk up to the directory root to find its config. See also
- [related nuget code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Settings/Settings.cs#L895)
- [blog stating nuget.config search behavior](http://blog.maartenballiauw.be/post/2014/03/11/NuGet-Configuration-File-inheritance-is-awesome.aspx)

I wonder what happens if the code lies on network shares but is that common?

**Comment by picrap** [comment]
Did you look at the code ? :mask: 
It simply goes up from project folder to drive root.
So no, I won't do it. Que dalle.

**Comment by vatirim** [comment]
I don't see the problem, nuget seems to work fine for many users and we would be in the same environment. But it is your choice.
