### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by Mogikan** [picrap/SignReferences#4]
Hello Pascal,

Could you be so kind to change the following code in you sources:
**ProcessUtility**
private static string FindApplicationPath(string fileName)
...
return path.Select(p => TryPath(p, fileName)).SingleOrDefault(p => p != null)
...
SingleOrDefault fails on some PC's. It's not that convenient to fix environment variables on all these PC-s. So, could you be so kind to change it to FirstOrDefault, thanks.

Kind Regards,
Vitaliy

**Comment by picrap** [comment]
Dam' right!

**Comment by picrap** [comment]
Fixed in 0.1.2.1.
